module.exports = {
    fireTube:               require('./fireTube'),
    redAlert:               require('./redAlert'),
    requestDock:            require('./requestDock'),
    sendKeyStroke:          require('./sendKeyStroke'),
    setAutoDamcon:          require('./setAutoDamcon'),
    setBeamFrequency:       require('./setBeamFrequency'),
    setCaptainTarget:       require('./setCaptainTarget'),
    setConsole:             require('./setConsole'),
    setGameMasterTarget:    require('./setGameMasterTarget'),
    setMainScreen:          require('./setMainScreen'),
    setReady:               require('./setReady'),
    setReady2:              require('./setReady2'),
    setScienceScan:         require('./setScienceScan'),
    setScienceTarget:       require('./setScienceTarget'),
    setShip:                require('./setShip'),
    setShipSettings:        require('./setShipSettings'),
    setWarp:                require('./setWarp'),
    setWeaponsTarget:       require('./setWeaponsTarget'),
    toggleAutoBeams:        require('./toggleAutoBeams'),
    togglePerspective:      require('./togglePerspective'),
    toggleReverseImpulse:   require('./toggleReverseImpulse'),
    toggleShields:          require('./toggleShields')
};